services:
  - type: web
    name: bitebridge-fullstack
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: APP_SEED_ENABLED
        value: true
      - key: APP_CORS_ALLOWED_ORIGIN_PATTERNS
        value: https://*.onrender.com
      - key: SPRING_DATA_MONGODB_DATABASE
        value: bitebridge
      - key: JWT_SECRET
        sync: false
      - key: SPRING_DATA_MONGODB_URI
        sync: false
